# Generated by Django 4.1.7 on 2023-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='tst', max_length=1000),
            preserve_default=False,
        ),
    ]
