# Generated by Django 4.1.7 on 2023-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='price_per_head',
            field=models.CharField(max_length=20),
        ),
    ]
