# Generated by Django 4.1.7 on 2023-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_reviewlikes_user_review_google_review_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='google_review_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
