# Generated by Django 4.1.7 on 2023-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_review_google_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='google_user_likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
