# Generated by Django 4.1.7 on 2023-06-11 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_google_rating_venue_total_google_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cover_photo',
            field=models.TextField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
